### ISSUE TITLE
Query not returning data

### ISSUE THREAD

**Issue by RudyShare** [Dragwar/sharp-dbhub#3]
When running a select query, the results are empty. It pulls the correct amount of rows (2) and columns (26), but the actual data for each field is empty. See screenshot below. It's the same issue for both live and non-live databases.

![image](https://github.com/Dragwar/sharp-dbhub/assets/117825750/c4d1edbc-9bf2-44a3-84b3-cb2796eac783)

```
var myDatabases = dbHubClient.GetDatabases(new SharpDbHub.Models.DatabasesRequest() { Live = true });
foreach (var db in myDatabases)
{
    dbName = db;
    break;
}
var myTables = dbHubClient.GetTables(new SharpDbHub.Models.TablesRequest(dbOwner, dbName));
byte[] byt = System.Text.Encoding.UTF8.GetBytes("SELECT * FROM POP_Production");
var sqlquery = Convert.ToBase64String(byt);
var results = dbHubClient.Query(new SharpDbHub.Models.QueryRequest(dbOwner, dbName, sqlquery));
```

**Comment by Dragwar** [comment]
please download [nuget](https://www.nuget.org/packages/SharpDbHub/) version 1.1.2 for the fix.

**Comment by RudyShare** [comment]
You're awesome, thanks it's working!
